/// @file hif2sc.cpp
/// @brief
/// Copyright (c) 2024-2025, Electronic Systems Design (ESD) Group,
/// Univeristy of Verona.
/// This file is distributed under the BSD 2-Clause License.
/// See LICENSE.md for details.

#include <iostream>

/////////////////////////////////////////
// Debug macros
/////////////////////////////////////////

#define HIF2SC_DEBUG_PRINT_STEP_FILES
#define HIF2SC_DEBUG_PRINT_BEFORE 1
//#define HIF2SC_PRINT_FINAL_TREE

#ifndef NDEBUG
//#define HIF2SC_CHECK_PARSING
#define HIF2SC_DEBUG_PREREFINEMENTS
#define HIF2SC_DEBUG_POSTREFINEMENTS
#endif

/////////////////////////////////////////
// HIF library includes
/////////////////////////////////////////

#include <hif/hif.hpp>

/////////////////////////////////////////
// Tool includes
/////////////////////////////////////////

#include "hif2sc/PostRefineMethods.hpp"
#include "hif2sc/PreRefineMethods.hpp"
#include "hif2sc/PrintMethods.hpp"
#include "hif2sc/PrintRefinementsVisitor.hpp"
#include "hif2sc/globals.hpp"
#include "hif2sc/hif2scParseLine.hpp"

/////////////////////////////////////////
// Utility functions prototypes
/////////////////////////////////////////

/// @brief Perform some refine of Hif description before the standardization.
/// The refinements must maintain correctness with the HIF semantics.
void perform_pre_refinement(hif::System &o, hif2scParseLine &cLine);

/// @brief Perform some refine of Hif description after the standardization.
/// The refinements are intended to make the code generated by the writing of
/// Hif description compilable.
void perform_post_refinement(hif::System &o, hif2scParseLine &cLine);

/// @brief Perform the generation of systemC code.
void perform_code_generation(hif::System &o, hif2scParseLine &cLine);

/// @brief Called on a stable system, perform all checks.
void checkStep(hif::System *s, const std::string &stepName, bool isFixed);

/// @brief Generate the step name.
auto getStepName(const std::string & /*n*/) -> std::string;

/////////////////////////////////////////
// global variables
/////////////////////////////////////////
namespace
{

hif::application_utils::StepFileManager _stepFileManager;

void _addScCoreLibrary(hif::Object *ref, hif::semantics::ILanguageSemantics *sem)
{
    // So, now we need to add sc_core librarydef and library.

    // Get the library definition.
    auto ld  = sem->getStandardLibrary("hif_systemc_sc_core");
    // Cast the reference to a system.
    auto sys = dynamic_cast<hif::System *>(ref);
    // If the reference is not a system, get the nearest parent system.
    if (sys == nullptr) {
        sys = hif::getNearestParent<hif::System>(ref);
    }
    // Prepare the options for adding the library definition.
    hif::manipulation::AddUniqueObjectOptions addOpt;
    addOpt.equalsOptions.checkOnlyNames = true;
    addOpt.position                     = 0;
    // Add the library definition to the system.
    hif::manipulation::addUniqueObject(ld, sys->libraryDefs, addOpt);
    // Prepare the HIF factory.
    hif::HifFactory factory(sem);
    // Create a library object.
    auto refl     = factory.library("hif_systemc_sc_core", nullptr, "", false, true);
    // Get the nearest scope.
    auto contents = hif::getNearestScope(ref, false, true, false);
    if (dynamic_cast<hif::Contents *>(contents) != nullptr) {
        contents = dynamic_cast<hif::Scope *>(contents->getParent());
    }
    // Prepare the options for adding the library.
    hif::manipulation::AddUniqueObjectOptions addOpt2;
    addOpt2.deleteIfNotAdded = true;
    // Add the library to the contents.
    hif::manipulation::addUniqueObject(refl, contents, addOpt2);
}

} // namespace

/////////////////////////////////////////
// hif2sc main function
/////////////////////////////////////////

auto main(int argc, char *argv[]) -> int
{
    hif::application_utils::initializeLogHeader("HIF2SC", "");

    // Get command line options and arguments.
    hif2scParseLine cLine(argc, argv);

    // Detect if verbose mode is active
    hif::application_utils::setVerboseLog(cLine.isVerbose());

    const std::string inputFile = cLine.getFiles().front();

#ifdef HIF2SC_DEBUG_PRINT_STEP_FILES
    _stepFileManager.setPrint(true);
#endif
    if (cLine.isAutostep()) {
        _stepFileManager.setAutoStepFile(inputFile);
    }

    // Read the system description.
    hif::System *pSys = dynamic_cast<hif::System *>(hif::readFile(inputFile));

    // Check the parsing.
    if (pSys == nullptr) {
        messageError(
            std::string("File : ") + cLine.getFiles().front() + "\n" + "\t\tWrong hif.xml system description.", nullptr,
            nullptr);
    }

    hif::semantics::HIFSemantics *hifLanguage         = hif::semantics::HIFSemantics::getInstance();
    hif::semantics::SystemCSemantics *systemcLanguage = hif::semantics::SystemCSemantics::getInstance();
    systemcLanguage->setStrictTypeChecks(true);

#ifdef HIF2SC_CHECK_PARSING
    if (hif::semantics::checkHif(pSys, hifLanguage) != 0) {
        std::clog << "\n\nWrong input HIF description." << std::endl;
        exit(1);
    }
    hif::semantics::resetDeclarations(pSys);
    hif::semantics::resetTypes(pSys);
    hif::manipulation::flushInstanceCache();
    hif::semantics::flushTypeCacheEntries();
#endif

    // Instruct semantics
    systemcLanguage->setKeepBit(cLine.keepBit());
    systemcLanguage->setResolvedTypes(cLine.useResolved());
    systemcLanguage->setUseHdtlib(cLine.useHDTLib());

    // Fix HIF description
    perform_pre_refinement(*pSys, cLine);

    if (_stepFileManager.checkStepName()) {
        // Perform standardization
        messageInfo(getStepName("Performing standardization"));
        _stepFileManager.startStep("STD");
        hif::semantics::standardizeDescription(pSys, hifLanguage, systemcLanguage, &_stepFileManager);

#if HIF2SC_DEBUG_PRINT_BEFORE
        _stepFileManager.endStep(pSys);
#endif

#ifdef HIF2SC_DEBUG_POSTREFINEMENTS
        messageInfo("After standardization checks");
        hif::semantics::UpdateDeclarationOptions dopt;
        dopt.forceRefresh = true;
        dopt.error        = true;
        hif::semantics::resetTypes(pSys);
        hif::manipulation::flushInstanceCache();
        hif::semantics::flushTypeCacheEntries();
        hif::semantics::updateDeclarations(pSys, systemcLanguage, dopt);
        hif::semantics::typeTree(pSys, systemcLanguage, true);
        hif::semantics::resetTypes(pSys);
#endif

#if !HIF2SC_DEBUG_PRINT_BEFORE
        _stepFileManager.endStep(pSys);
#endif
    }

    // Fix standardized HIF description
    // Note: include TLM refinement and (optional) use of HDTlib
    perform_post_refinement(*pSys, cLine);

    // Preliminary check on directory structure
    messageInfo("Generating output directory structure");
    auto pdsRepository = new hif::backends::CHifDirStruct(*pSys, cLine.getOutputDirectory().c_str());
    auto status        = pdsRepository->Check();
    if ((status != hif::backends::CHifDirStruct::DST_OK) && (status != hif::backends::CHifDirStruct::DST_ALRDY_EXIST)) {
        pdsRepository->printError(status);
    }

    // SystemC code generation
    if (_stepFileManager.checkStepName()) {
        perform_code_generation(*pSys, cLine);
    }

    // Print translation warnings
    printUniqueWarnings("During translation, one or more warnings have been raised:");

    // Update date files
    pdsRepository->UpdateDates();

    // Memory clean
    hif::manipulation::flushInstanceCache();
    hif::semantics::flushTypeCacheEntries();
    delete pdsRepository;
    delete pSys;

    // Command done
    std::string command;
    for (int i = 0; i < argc; i++) {
        command += std::string(argv[i]) + " ";
    }
    messageInfo(" -- Command \"" + command + "\" Done --");

    hif::application_utils::restoreLogHeader();
    return 0;
}

/////////////////////////////////////////
// Utility functions implementations
/////////////////////////////////////////

#ifdef NDEBUG
void checkStep(hif::System *s, const std::string &stepName, bool /*isFixed*/)
#else
void checkStep(hif::System *s, const std::string &stepName, bool isFixed)
#endif
{

#if HIF2SC_DEBUG_PRINT_BEFORE
    _stepFileManager.printStep(s, stepName);
#endif

#ifdef HIF2SC_DEBUG_PREREFINEMENTS
    if (isFixed) {
        messageInfo(("   Checking step: " + stepName));

        auto hifLanguage = hif::semantics::HIFSemantics::getInstance();

        hif::semantics::CheckOptions opt;
        opt.checkFlushingCaches = true;
        opt.checkSimplifiedTree = true;

        if (hif::semantics::checkHif(s, hifLanguage, opt) != 0) {
            std::clog << "\nWrong HIF description after " << stepName << '\n';
            assert(false);
            exit(1);
        }
    }
#endif

#if !HIF2SC_DEBUG_PRINT_BEFORE
    _stepFileManager.printStep(s, stepName);
#endif
}

auto getStepName(const std::string &n) -> std::string
{
    std::stringstream s;
    const int nr = _stepFileManager.getStepNumber();
    if (nr < 10) {
        s << "0";
    }
    s << nr;
    s << " " << n;
    return s.str();
}

void perform_pre_refinement(hif::System &o, hif2scParseLine &cLine)
{
    messageInfo("Performing refinement steps...");

    auto hifSem = hif::semantics::HIFSemantics::getInstance();

    auto sysCSem = hif::semantics::SystemCSemantics::getInstance();

    // ////////////////////////////
    // Fix nested declarations
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Fixing nested declarations"));
        hif::manipulation::fixNestedDeclarations(&o, hifSem);

        checkStep(&o, "PreRefine_fixNestedBadDeclaration", true);
    }

    // ////////////////////////////
    // Fix generates
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Fixing generate statements"));
        bool fixed = hif::manipulation::expandGenerates(&o, hifSem);
        if (fixed) {
            messageWarning("Generate statements have been expanded.", nullptr, nullptr);
        }

        checkStep(&o, "PreRefine_expandGenerates", fixed);
    }

    // ////////////////////////////
    // Fix bad template parameters.
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Fixing troublesome template parameters"));
        _addScCoreLibrary(&o, hifSem);
        hif::manipulation::FixTemplateOptions opt;
        opt.checkSem                = sysCSem;
        opt.setConstExpr            = true;
        opt.useHdtLib               = cLine.useHDTLib();
        opt.fixStandardDeclarations = true;
        hif::manipulation::fixTemplateParameters(&o, hifSem, opt);
        checkStep(&o, "PreRefine_templateParameters", true);
    }

    // ////////////////////////////
    // Fix instance bindings
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Fixing port bindings of component instances"));
        hif::manipulation::FixBindingOptions bindOpts;
        bindOpts.allowOnlySignalPorts = true;
        hif::manipulation::fixInstanceBindings(&o, hifSem, bindOpts);
        checkStep(&o, "PreRefine_instanceBindings", true);
    }

    // ////////////////////////////
    // Fix multiple write on signals/ports.
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Fixing multiple signal/port assignments"));
        hif::manipulation::fixMultipleSignalPortAssigns(&o, hifSem);
        checkStep(&o, "PreRefine_multipleSignalPortAssigns", true);
    }

    // ////////////////////////////
    // Rebase type span ("0 upto X" or "X downto 0").
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Rebasing type spans"));
        hif::manipulation::rebaseTypeSpan(&o, hifSem, false);
        // Need cleanup.
        hif::semantics::resetTypes(&o);
        hif::manipulation::flushInstanceCache();
        hif::semantics::flushTypeCacheEntries();
        hif::manipulation::simplify(&o, hifSem);
        checkStep(&o, "rebaseTypeSpan", true);
    }

    // ////////////////////////////
    // Revert upto ranges to downto.
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Fixing direction of ranges"));
        hif::manipulation::fixRangesDirection(&o, hifSem);
        checkStep(&o, "PreRefine_ranges", true);
    }

    // ////////////////////////////
    // Fix conflicting sub declaration.
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Fixing conflicting subprograms"));
        bool fixed = fixConflictingSubPrograms(&o, cLine.keepBit(), hifSem);
        checkStep(&o, "PreRefine_conflictingSupPrograms", fixed);
    }

    // ////////////////////////////
    // Expand aliases.
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Expanding aliases"));
        hif::manipulation::expandAliases(&o, hifSem);
        checkStep(&o, "expandAliases", true);
    }

    // ////////////////////////////
    // Miscellaneous fixes
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Performing miscellaneous fixes"));
        fixMiscIssues(&o, hifSem, sysCSem);
        checkStep(&o, "PreRefine_misc", true);
    }

    // ////////////////////////////
    // Introducing utility libraries.
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Introducing support utility libraries"));
        bool fixed = fixUtilityLibraries(&o, hifSem, cLine);
        checkStep(&o, "fixUtilityLibraries", fixed);
    }
}

void perform_post_refinement(hif::System &o, hif2scParseLine &cLine)
{
    auto sysCSem = hif::semantics::SystemCSemantics::getInstance();

    // ////////////////////////////
    // Adding sc_core library
    // ////////////////////////////
    if (!cLine.useHDTLib()) {
        auto coreLib = sysCSem->getStandardLibrary("sc_core");
        hif::manipulation::AddUniqueObjectOptions addOpt;
        addOpt.equalsOptions.checkOnlyNames = true;
        addOpt.position                     = 0;
        hif::manipulation::addUniqueObject(coreLib, o.libraryDefs, addOpt);
    }

    // ////////////////////////////
    // Refine for C++98 compatibility
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        if (cLine.useCpp98()) {
            messageInfo(getStepName("Refining for C++98 standard compliance"));
            cpp98StandardRefinements(&o, cLine, sysCSem, sysCSem);
        }
        _stepFileManager.printStep(&o, "Refining_to_C++98");
    }

    // ////////////////////////////
    // Optimize HIF tree w.r.t.
    // generated code
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        if (cLine.isOptimized()) {
            messageInfo(getStepName("Optimizing code"));
            postRefinementsOptimizationStep(&o, cLine, sysCSem);
        }
        _stepFileManager.printStep(&o, "Tree_optimization");
    }

    // ////////////////////////////
    // Final operations of HIF tree
    // ////////////////////////////
    if (_stepFileManager.checkStepName()) {
        messageInfo(getStepName("Performing final manipulations"));
        postRefinementsFinalStep(&o, cLine, sysCSem);
        _stepFileManager.printStep(&o, "Final_manipulations");
    }

    messageInfo("Refinement steps completed.");
}

void perform_code_generation(hif::System &o, hif2scParseLine &cLine)
{
    // Note: do not change order of visitors
    messageInfo("Generating code...");

    // Print of final tree.
#ifdef HIF2SC_PRINT_FINAL_TREE
    _stepFileManager.setPrint(true);
    _stepFileManager.printStep(&o, "Final_tree");
#endif

    auto syscSem = hif::semantics::SystemCSemantics::getInstance();

    PrintSystemCVisitor::ConstTemplateMap ctmList;
    collectConstTemplates(&o, ctmList, syscSem);
    printHeaders(&o, cLine, ctmList);
    printRefinements(&o, syscSem);
    printImplementations(&o, cLine, ctmList);
    PrintSystemCVisitor::clearConstTemplateMap(ctmList);

    messageInfo("Code generation completed.");
}
