/// @file hif2verilog.cpp
/// @brief
/// Copyright (c) 2024-2025, Electronic Systems Design (ESD) Group,
/// Univeristy of Verona.
/// This file is distributed under the BSD 2-Clause License.
/// See LICENSE.md for details.

#include <iostream>

#define HIF2VERILOG_DEBUG_PRINT_STEP_FILES
#define HIF2VERILOG_DEBUG_PRINT_BEFORE 1
#define HIF2VERILOG_PRINT_FINAL_TREE

#ifndef NDEBUG
//#define HIF2VERILOG_CHECK_PARSING
#define HIF2VERILOG_DEBUG_PREREFINEMENTS
#define HIF2VERILOG_DEBUG_POSTREFINEMENTS
#endif

#include <hif/hif.hpp>

#include "hif2verilog/PrintVerilogMethods.hpp"
#include "hif2verilog/hif2verilogParseLine.hpp"

using namespace hif;
using std::string;

/////////////////////////////////////////
// Utility functions prototypes
/////////////////////////////////////////

/// @brief Perform some refine of HIF description before the standardization.
/// The refinements must maintain correctness with the HIF semantics.
void perform_pre_refinement(hif::System &o, hif2verilogParseLine &cLine);

/// @brief Perform some refine of HIF description after the standardization.
/// The refinements are intended to make the code generated by the writing of
/// Hif description compilable.
void perform_post_refinement(hif::System &o, hif2verilogParseLine &cLine);

/// @brief Perform the generation of Verilog/AMS code.
void perform_code_generation(hif::System &o, hif2verilogParseLine &cLine);

/// @brief Called on a stable system, perform all required checks.
void checkStep(System *s, const std::string &stepName, bool fixed);

/// @brief Generate the step name.
auto getStepName(const std::string & /*n*/) -> std::string;

/////////////////////////////////////////
// global variables
/////////////////////////////////////////
namespace
{
/// @brief Keep count of current step number.
hif::application_utils::StepFileManager _stepFileManager;
} // namespace

/////////////////////////////////////////
// hif2verilog main function
/////////////////////////////////////////

auto main(int argc, char *argv[]) -> int
{
    hif::application_utils::initializeLogHeader("HIF2VERILOG", "");

    // Get command line options and arguments.
    hif2verilogParseLine cLine(argc, argv);

    // Detect if verbose mode is active
    hif::application_utils::setVerboseLog(cLine.isVerbose());

    const std::string inputFile = cLine.getFiles().front();

#ifdef HIF2VERILOG_DEBUG_PRINT_STEP_FILES
    _stepFileManager.setPrint(true);
#endif
    if (cLine.isAutostep()) {
        _stepFileManager.setAutoStepFile(inputFile);
    }

    // Read the system description.
    System *pSys = dynamic_cast<System *>(hif::readFile(inputFile));

    // Check the parsing.
    if (pSys == nullptr) {
        messageError(
            std::string("File : ") + inputFile + "\n" + "\t\tWrong hif.xml system description.", nullptr, nullptr);
    }

    hif::semantics::HIFSemantics *hifLanguage         = hif::semantics::HIFSemantics::getInstance();
    hif::semantics::VerilogSemantics *verilogLanguage = hif::semantics::VerilogSemantics::getInstance();
    verilogLanguage->setStrictTypeChecks(true);

#ifdef HIF2VERILOG_CHECK_PARSING
    if (hif::semantics::checkHif(pSys, hifLanguage) != 0) {
        std::clog << "\n\nWrong input HIF description." << std::endl;
        exit(1);
    }
    hif::semantics::resetDeclarations(pSys);
    hif::semantics::resetTypes(pSys);
    hif::manipulation::flushInstanceCache();
    hif::semantics::flushTypeCacheEntries();
#endif

    // Instruct semantics to allows correct expressions

    // Pre-refinement to fix the HIF description
    perform_pre_refinement(*pSys, cLine);
    if (0) {
        messageInfo("" + hif::languageIDToString(pSys->getLanguageID()));

        // Without this block here the code don't work.
        if (hif::languageIDToString(pSys->getLanguageID()) == "AMS") {
            pSys->libraryDefs.push_back(verilogLanguage->getStandardLibrary("vams_standard"));
            // The following code is a workaround until the inclusion issue will be fixed in lexer
            pSys->libraryDefs.push_back(verilogLanguage->getStandardLibrary("vams_constants"));
            pSys->libraryDefs.push_back(verilogLanguage->getStandardLibrary("vams_disciplines"));
            pSys->libraryDefs.push_back(verilogLanguage->getStandardLibrary("vams_driver_access"));
            hif::HifFactory f(verilogLanguage);
            pSys->libraries.push_back(f.library("vams_standard", nullptr, "", false, true));
            pSys->libraries.push_back(f.library("vams_constants", nullptr, "", false, true));
            pSys->libraries.push_back(f.library("vams_disciplines", nullptr, "", false, true));
            pSys->libraries.push_back(f.library("vams_driver_access", nullptr, "", false, true));
        } else { // To check.
            pSys->libraryDefs.push_back(verilogLanguage->getStandardLibrary("standard"));
            hif::HifFactory f(verilogLanguage);
            pSys->libraries.push_back(f.library("standard", nullptr, "", false, true));
        }
        verilogLanguage->addStandardPackages(pSys);
        _stepFileManager.printStep(pSys, "addStandardPackages");
    }

    if (0) {
        // Check if it is necessary for this back-end.
        hif::manipulation::renameConflictingDeclarations(pSys, verilogLanguage, nullptr, "inst");
        _stepFileManager.printStep(pSys, "renameConflictingDeclarations");

        //if (_stepFileManager.checkStepName())

        // Perform standardization
        messageInfo(getStepName("Performing standardization"));
        _stepFileManager.startStep("STD");
        hif::semantics::standardizeDescription(pSys, hifLanguage, verilogLanguage, &_stepFileManager);

#if HIF2VERILOG_DEBUG_PRINT_BEFORE
        _stepFileManager.endStep(pSys);
#endif

#ifdef HIF2VERILOG_DEBUG_POSTREFINEMENTS
        messageInfo("After standardization checks");
        hif::semantics::UpdateDeclarationOptions dopt;
        /// @todo: check what options must be true
        dopt.forceRefresh = true;
        dopt.error        = true;
        hif::semantics::resetTypes(pSys);
        hif::manipulation::flushInstanceCache();
        hif::semantics::flushTypeCacheEntries();
        hif::semantics::updateDeclarations(pSys, verilogLanguage, dopt);
        hif::semantics::typeTree(pSys, verilogLanguage, true);
        hif::semantics::resetTypes(pSys);
#endif

#if !HIF2VERILOG_DEBUG_PRINT_BEFORE
        _stepFileManager.endStep(pSys);
#endif
    }

    // Fix standardized HIF description
    perform_post_refinement(*pSys, cLine);

    // Preliminary check on directory structure
    messageInfo("Directory structure generation.");
    auto *pdsRepository = new hif::backends::CHifDirStruct(*pSys, cLine.getOutputDirectory().c_str());
    auto status         = pdsRepository->Check();
    if ((status != hif::backends::CHifDirStruct::DST_OK) && (status != hif::backends::CHifDirStruct::DST_ALRDY_EXIST)) {
        pdsRepository->printError(status);
    }

    // Verilog code generation
    if (_stepFileManager.checkStepName()) {
        perform_code_generation(*pSys, cLine);
    }

    // Print translation warnings
    printUniqueWarnings("During translation, one or more warnings have been raised:");

    // Update date files
    pdsRepository->UpdateDates();

    // Memory clean
    hif::manipulation::flushInstanceCache();
    hif::semantics::flushTypeCacheEntries();
    delete pdsRepository;
    // TODO
    //delete pSys;

    // Command done
    string command;
    for (int i = 0; i < argc; i++) {
        command += string(argv[i]) + " ";
    }
    messageInfo(" -- Command \"" + command + "\" Done --");

    hif::application_utils::restoreLogHeader();
    return 0;
}

/////////////////////////////////////////
// Utility functions implementations
/////////////////////////////////////////

#ifdef NDEBUG
void checkStep(System *s, const std::string &stepName, const bool /*isFixed*/)
#else

void checkStep(System *s, const std::string &stepName, const bool isFixed)
#endif
{
#if HIF2VERILOG_DEBUG_PRINT_BEFORE
    _stepFileManager.printStep(s, stepName);
#endif

#ifdef HIF2VERILOG_DEBUG_PREREFINEMENTS
    if (isFixed) {
        messageInfo(("   Checking step: " + stepName));

        hif::semantics::ILanguageSemantics *hifLanguage = hif::semantics::HIFSemantics::getInstance();

        hif::semantics::CheckOptions opt;
        opt.checkFlushingCaches = true;
        opt.checkSimplifiedTree = true;
        //opt.checkOnCopy = true;

        if (hif::semantics::checkHif(s, hifLanguage, opt) != 0) {
            std::clog << "\nWrong HIF description after " << stepName << '\n';
            assert(false);
            exit(1);
        }
    }
#endif

#if !HIF2VERILOG_DEBUG_PRINT_BEFORE
    _stepFileManager.printStep(s, stepName);
#endif
}

auto getStepName(const std::string &n) -> std::string
{
    std::stringstream s;
    const int nr = _stepFileManager.getStepNumber();
    if (nr < 10) {
        s << "0";
    }
    s << nr;
    s << " " << n;
    return s.str();
}

void perform_pre_refinement(System & /*o*/, hif2verilogParseLine & /*cLine*/) {}

void perform_post_refinement(System & /*o*/, hif2verilogParseLine & /*cLine*/) {}

void perform_code_generation(System &o, hif2verilogParseLine &cLine)
{
    // Note: do not change order of visitors
    messageInfo("Code generation");

    // Print of final tree.
#ifdef HIF2VERILOG_PRINT_FINAL_TREE
    _stepFileManager.setPrint(true);
    _stepFileManager.printStep(&o, "Final_tree");
#endif

    printVerilog(&o, cLine);
    messageInfo("Code generation completed.");
}
