/// @file hif2vhdl.cpp
/// @brief
/// Copyright (c) 2024-2025, Electronic Systems Design (ESD) Group,
/// Univeristy of Verona.
/// This file is distributed under the BSD 2-Clause License.
/// See LICENSE.md for details.

#include <iostream>

/////////////////////////////////////////
// Debug macros
/////////////////////////////////////////

//#define HIF2VHDL_DEBUG_PRINT_STEP_FILES
#define HIF2VHDL_DEBUG_PRINT_BEFORE 1
//#define HIF2VHDL_PRINT_FINAL_TREE

#ifndef NDEBUG
//#define HIF2VHDL_CHECK_PARSING
#define HIF2VHDL_DEBUG_PREREFINEMENTS
#define HIF2VHDL_DEBUG_POSTREFINEMENTS
#endif

/////////////////////////////////////////
// HIF library includes
/////////////////////////////////////////
#include <hif/hif.hpp>

/////////////////////////////////////////
// Tool includes
/////////////////////////////////////////

#include "hif2vhdl/PostRefineMethods.hpp"
#include "hif2vhdl/PreRefineMethods.hpp"
#include "hif2vhdl/PrintMethods.hpp"
#include "hif2vhdl/hif2vhdlParseLine.hpp"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-parameter"
#endif

/////////////////////////////////////////
// Namespaces
/////////////////////////////////////////

using namespace hif;

/////////////////////////////////////////
// Utility functions prototypes
/////////////////////////////////////////

/// @brief Perform some refine of Hif description before the standardization.
/// The refinements must maintain correctness with the HIF semantics.
void perform_pre_refinement(hif::System &o, int &stepName);

/// @brief Perform some refine of Hif description after the standardization.
/// The refinements are intended to make the code generated by the writing of
/// Hif description compilable.
void perform_post_refinement(hif::System &o, int &stepName);

/// @brief Perform the generation of systemC code.
void perform_code_generation(hif::System &o, const std::string &outDir);

/// @brief Print the step files in new and old formats.
void printStep(System *s, std::string &stepName);

/// @brief Called on a stable system, perform all checks.
void checkStep(System *s, std::string &stepName);

/// @brief Check if given stepName is the same of currentStep.
auto checkStepName(int &stepName) -> bool;

/// @brief Generate the step name.
auto getStepName(const std::string & /*n*/) -> std::string;

/////////////////////////////////////////
// global variables
/////////////////////////////////////////
namespace
{
/// @brief Keep count of current step number.
int stepNr = -1;
} // namespace

/////////////////////////////////////////
// hif2vhdl main function
/////////////////////////////////////////

auto main(int argc, char *argv[]) -> int
{
    hif::application_utils::initializeLogHeader("HIF2VHDL", "");

    // Get command line options and arguments.
    hif2vhdlParseLine cLine(argc, argv);

    // Detect if verbose mode is active
    hif::application_utils::setVerboseLog(cLine.isVerbose());

    if (cLine.isPrintOnly()) {
        ReadHifOptions opt;
        opt.sem      = hif::semantics::VHDLSemantics::getInstance();
        auto *pSys = dynamic_cast<System *>(hif::readFile(cLine.getFiles().front(), opt));

        perform_code_generation(*pSys, cLine.getOutputDirectory());
        return 0;
    }

    // Read the system description.
    System *pSys = dynamic_cast<System *>(hif::readFile(cLine.getFiles().front()));

    // Check the parsing.
    if (pSys == nullptr) {
        messageError(
            std::string("File : ") + cLine.getFiles().front() + "\n" + "\t\tWrong hif.xml system description.", nullptr,
            nullptr);
    }

    // TODO Enable when standardization will be needed
    hif::semantics::HIFSemantics *hifLanguage   = hif::semantics::HIFSemantics::getInstance();
    hif::semantics::VHDLSemantics *vhdlLanguage = hif::semantics::VHDLSemantics::getInstance();

#ifdef HIF2VHDL_CHECK_PARSING
    if (hif::semantics::checkHif(pSys, hifLanguage) != 0) {
        std::clog << "\n\nWrong input HIF description." << std::endl;
        exit(1);
    }
    hif::semantics::resetDeclarations(pSys);
    hif::semantics::resetTypes(pSys);
    hif::manipulation::flushInstanceCache();
    hif::semantics::flushTypeCacheEntries();
#endif

    // Fix HIF description
    perform_pre_refinement(*pSys, cLine.getStep());

    if (checkStepName(cLine.getStep())) {
        // Perform standardization
        messageInfo(getStepName("Performing standardization"));

        // TODO Enable when standardization will be needed
        hif::semantics::standardizeDescription(pSys, hifLanguage, vhdlLanguage);

#if (defined HIF2VHDL_DEBUG_PRINT_STEP_FILES) && HIF2VHDL_DEBUG_PRINT_BEFORE
        printStep(pSys, "standardizeDescription");
#endif

#ifdef HIF2VHDL_DEBUG_POSTREFINEMENTS
        messageInfo("After standardization checks");
        hif::semantics::UpdateDeclarationOptions dopt;
        dopt.forceRefresh = true;
        dopt.error        = true;

        hif::semantics::resetTypes(pSys);
        hif::manipulation::flushInstanceCache();
        hif::semantics::flushTypeCacheEntries();
        hif::semantics::updateDeclarations(pSys, vhdlLanguage, dopt);
        hif::semantics::typeTree(pSys, vhdlLanguage, true);
        hif::semantics::resetTypes(pSys);
#endif

#if (defined HIF2VHDL_DEBUG_PRINT_STEP_FILES) && !HIF2VHDL_DEBUG_PRINT_BEFORE
        printStep(pSys, "standardizeDescription");
#endif
    }

    // Fix standardized HIF description
    perform_post_refinement(*pSys, cLine.getStep());

    // Preliminary check on directory structure
    messageInfo("Directory structure generation.");
    auto *pdsRepository = new hif::backends::CHifDirStruct(*pSys, cLine.getOutputDirectory().c_str());
    auto status         = pdsRepository->Check();
    if ((status != hif::backends::CHifDirStruct::DST_OK) && (status != hif::backends::CHifDirStruct::DST_ALRDY_EXIST)) {
        pdsRepository->printError(status);
    }

    // VHDL code generation
    if (checkStepName(cLine.getStep())) {
        perform_code_generation(*pSys, cLine.getOutputDirectory());
    }

    // Print translation warnings
    printUniqueWarnings("During translation, one or more warnings have been raised:");

    // Update date files
    pdsRepository->UpdateDates();

    // Memory clean
    delete pdsRepository;
    delete pSys;

    // Command done
    std::string command;
    for (int i = 0; i < argc; i++) {
        command += std::string(argv[i]) + " ";
    }
    messageInfo(" -- Command \"" + command + "\" Done --");

    hif::application_utils::restoreLogHeader();
    return 0;
}

/////////////////////////////////////////
// Utility functions implementations
/////////////////////////////////////////

void printStep(System *s, const std::string &stepName)
{
    std::stringstream ssName;
    ssName << hif::application_utils::getApplicationName() << "_" << stepNr << "_" << stepName;

    hif::PrintHifOptions opt;
    opt.printHifStandardLibraries = true;
    hif::writeFile(ssName.str(), s, true, opt);
    hif::writeFile(ssName.str(), s, false, opt);
}

void checkStep(System *s, const std::string &stepName)
{
    (void)s;
#if (defined HIF2VHDL_DEBUG_PRINT_STEP_FILES) && HIF2VHDL_DEBUG_PRINT_BEFORE
    printStep(s, stepName);
#endif

#ifdef HIF2VHDL_DEBUG_PREREFINEMENTS
    messageInfo(("Checking step: " + stepName));

    hif::semantics::ILanguageSemantics *hifLanguage = hif::semantics::HIFSemantics::getInstance();

    hif::semantics::CheckOptions opt;
#if 1
    opt.checkFlushingCaches = true;
    opt.checkSimplifiedTree = true;
    //opt.checkOnCopy = true;
#else
    hif::manipulation::flushInstanceCache();
    hif::semantics::flushTypeCacheEntries();
    hif::semantics::resetTypes(s);
    hif::semantics::updateDeclarations(s, hifLanguage, false, true);
    hif::manipulation::simplify(s, hifLanguage);
    hif::semantics::typeTree(s, hifLanguage, true);
#endif

    if (hif::semantics::checkHif(s, hifLanguage, opt) != 0) {
        std::clog << "\nWrong HIF description after " << stepName << '\n';
        assert(false);
        exit(1);
    }
#endif

#if (defined HIF2VHDL_DEBUG_PRINT_STEP_FILES) && !HIF2VHDL_DEBUG_PRINT_BEFORE
    printStep(s, stepName);
#endif
}

auto checkStepName(int &stepName) -> bool
{
    ++stepNr;
    if (stepName == -1) {
        return true;
    }
    if (stepNr != stepName) {
        return false;
    }
    stepName = -1;
    return true;
}

auto getStepName(const std::string &n) -> std::string
{
    std::stringstream s;
    s << stepNr;
    s << " " << n;
    return s.str();
}

void perform_pre_refinement(System &o, int &stepName)

{
    messageInfo("Refinements steps");

    hif::semantics::ILanguageSemantics *hifSem = hif::semantics::HIFSemantics::getInstance();

    // ////////////////////////////
    // Fix identifier names
    // ////////////////////////////
    if (checkStepName(stepName)) {
        messageInfo(getStepName("Fixing identifier names"));
        fixIdentifierNames(&o, hifSem);

        checkStep(&o, "fixIdentifierNames");
    }

    // ////////////////////////////
    // Fix read output ports
    // ////////////////////////////
    if (checkStepName(stepName)) {
        messageInfo(getStepName("Fixing read output ports"));
        fixReadOutPorts(&o, hifSem);

        checkStep(&o, "fixReadOutPorts");
    }

    // ////////////////////////////
    // Miscellaneous fixes
    // ////////////////////////////
    if (checkStepName(stepName)) {
        messageInfo(getStepName("Performing miscellaneous fixes"));
        fixMiscIssues(&o, hifSem);

        checkStep(&o, "PreRefine_misc");
    }

    // ////////////////////////////
    // Fix instance bindings
    // ////////////////////////////
    if (checkStepName(stepName)) {
        messageInfo(getStepName("Fixing port bindings of component instances"));

        hif::manipulation::FixBindingOptions opt;
        opt.fixSlices  = false;
        opt.fixMembers = false;
        opt.fixOthers  = false;
        hif::manipulation::fixInstanceBindings(&o, hifSem, opt);

        checkStep(&o, "PreRefine_instanceBindings");
    }

    // ////////////////////////////
    // Introducing utility libraries.
    // ////////////////////////////
    if (checkStepName(stepName)) {
        messageInfo(getStepName("Introducing support utility libraries"));

        if (fixUtilityLibraries(&o, hifSem)) {
            checkStep(&o, "fixUtilityLibraries");
        }
    }
}

void perform_post_refinement(System &s, int &stepName)
{
    messageInfo("Performing refinements steps...");

    hif::semantics::ILanguageSemantics *vhdlSem = hif::semantics::VHDLSemantics::getInstance();

    // ////////////////////////////
    // Final operations of HIF tree
    // ////////////////////////////
    if (checkStepName(stepName)) {
        messageInfo(getStepName("Performing final manipulations"));
        postRefinementsFinalStep(&s, vhdlSem);

#ifdef HIF2VHDL_DEBUG_PRINT_STEP_FILES
        printStep(&s, "Final_manipulations");
#endif
    }

    messageInfo("Refinement steps completed.");
}

void perform_code_generation(System &o, const std::string &outDir)
{
    // Note: do not change order of visitors
    messageInfo("Generating code...");

    // Print of final tree.
#ifdef HIF2VHDL_PRINT_FINAL_TREE
    printStep(&o, "Final_tree");
#endif

    printVHDL(&o, outDir);

    messageInfo("Code generation completed.");
}
